# Generated by Django 5.1.1 on 2024-11-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productentry',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
